# Generated by Django 5.1.7 on 2025-03-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='url_imagee',
            new_name='url_image',
        ),
    ]
