# Generated by Django 5.1.7 on 2025-03-30 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0001_initial'),
        ('mensajes', '0002_rename_url_imagee_mensaje_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='conversaciones.conversacion'),
        ),
    ]
