# Generated by Django 5.1.7 on 2025-04-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_mensaje_conversacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='url_image',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='url_photo',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
