# Generated by Django 5.1.4 on 2025-03-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracionesaplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionaplicacion',
            name='idioma',
            field=models.CharField(default='es', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracionaplicacion',
            name='tema',
            field=models.CharField(default='light', max_length=50),
        ),
    ]
