# Generated by Django 5.1.4 on 2025-03-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
