# Generated by Django 5.1.4 on 2025-03-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_apm_remove_user_app_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
