# Generated by Django 5.1.4 on 2025-03-17 04:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_url_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
