# Generated by Django 5.1.4 on 2025-03-17 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_token_expired_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 22, 37, 7, 59435)),
        ),
    ]
