# Generated by Django 5.1.4 on 2025-03-17 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_token_created_alter_token_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='key',
            new_name='key_pass',
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 23, 52, 20, 263688)),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 23, 53, 20, 263688)),
        ),
    ]
