# Generated by Django 5.1.4 on 2025-03-17 06:32

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_key_token_key_pass_alter_token_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 0, 32, 1, 887262)),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 0, 33, 1, 887262)),
        ),
        migrations.CreateModel(
            name='TokenRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_recovery', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2025, 3, 17, 0, 32, 1, 887262))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
