# Generated by Django 5.1.7 on 2025-03-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0002_alter_conversacion_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='alias_grupo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
