# Generated by Django 5.1.7 on 2025-04-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0004_conversacion_url_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='url_photo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
